name: SeichiStat
main: com.github.unchama.seichistat.SeichiStat
version: 0.1.0

commands:
  seichistat:
      description: This is a stat command.
      usage: /<command> <help>
      permission: seichistat.command
      permission-message: You don't have <permission>